version: '3'
services:
  python3:
    restart: always
    # Build the image from the Dockerfile
    build:
      context: .
      dockerfile: Dockerfile

    container_name: 'python_face_recognition'
    working_dir: /python/app
    tty: true
    volumes:
        - .:/python/app

    # Macのカメラを使う場合
    devices:
      - /dev/video0:/dev/video0